spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:interview
  mvc:
    date-format: yyyy-MM-dd
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  level:
    com.profectus.interview: info
  file:
    name: profectus.log
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
---
spring:
  profiles: dev
server:
  port: 8080
---
spring:
  profiles: test
server:
  port: 8081