spring:
  profiles:
    active: product
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  mvc:
    date-format: yyyy-MM-dd
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
logging:
  level:
    com.profectus.interview: debug
  file:
    name: profectus.log
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
server:
  servlet:
    context-path: /profectus-1
  port: 8080
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/profectus?useSSL=false&serverTimezone=UTC
    username: root
    password: root123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  profiles: product
  datasource:
    platform: h2
    url: jdbc:h2:mem:interview

